module.exports = {
	"success_code": 200,
	"unauthorized_code": 401,
	"forbidden_code": 403,
	"bad_request_code": 400,
	"server_error_code": 500,
	"accepted_code": 202,

	"per_page_limit": 5,
	'site_title': 'Demo',
	'forgot_password_subject': 'Demo: Reset your password.',
	'auth_code_subject': 'Demo: Authorization Code.',
	'activation_subject': 'Activate your account',
	'resent_activation_subject': 'Resend activation email ,  activate your account.',
	'sendAuthCode': 'Two Factor auth code sent.',
	'user2factorVerify': '2factor auth code verified.',
	'activation_subject_2factor': 'Two Factor Verification.',
	'create_message': 'wallet successfully created.',
	'email_registration_invalid': 'Invalid Credentials.',
	'loan_state_active': 'loan state has been changed to Active successfully.',
	'partially_loan_success': 'Partially funded loan started successfully.',
	'remaining_smart_contract': 'Remaining Smart Contract created Successfully.',
	'update2fa': 'Two factor authentication enabled/disabled successfully.',

	'process_done': 'Your process done successfully.',
	'sent_activation_email': "Successfully sent activation email.",
	'resent_activation_email': "Successfully resent verification email.",
	'invalid_login_credentials': 'Invalid Credentials.',
	'server_error': 'Oops! Something went wrong.',
	'fund_error': 'insufficient funds.Please check your Wallet Balance.',
	'borrower_fund_error': 'Borrower have insufficient funds to proceed with the loan',
	'unauthorized': 'You are unauthorized user to access this url.',
	'token_expired': 'Your token is expired. Please login again.',
	'insufficient_parameters': 'Insufficient parameters have been passed.',
	'invalid_login_credentials': 'Incorrect email or password.',
	'success_login': 'Successfully logged in.',
	'inavalid_otp': 'Invalid Two Factor Code.',
	'success_logout': 'Successfully logged out.',
	'forgotp_password_link': 'Reset password link has been sent to your email.',
	'password_reset_success': 'Your password reset successfully.',
	'invalid_password_link': 'Invalid password reset link.',
	'ether_transfer_success': ' ETH has been transferred successfully.',
	'clp_transfer_success': ' CLP has been transferred successfully.',
	'eth_transaction': 'Ethereum transaction successfully done.',
	'ethereum_address_invalid': 'Ether address is invalid or Account does not have enough balance.',
	'same_ether_address': 'You can not transfer to your own Account.',
	'otp_continue': 'please check your email and verify otp.',
	'otp_not_currect': 'otp not correct.',
	'ether_transaction_list': 'Ether Transaction List.',
	'clp_transaction_list': 'CLP Transaction List.',
	'get_maxclpeth': 'Maximum CLP and Maximum Ether value listed Successfully.',
	'update_clpeth': 'Maximum CLP and Maximum Ether value updated Successfully.',

	'all_lists_details': 'All lists deteails retrived successfully.',
	'invalid_auth_code': 'Invalid Authorization code.',
	'auth_code_expire': "Your Authorization Code has been expired.",
	'activate_your_account': 'Activation link has been sent to your email. Please check your email to activate your account.',
	'activate_account_success': 'Your account has been activated successfully.',
	'insuccess_loginvalid_password_link': 'Activation link has been expired.',
	'invalid_password_link': 'Reset password link has been expired.',
	'email_not_exist': 'Please activate your account from the link in your email OR contact the administrator to activate your account.',
	'email_exist': 'Email already exist.',
	'email_not_found': 'If your email address is registered in our system, you will receive an email to reset password.',
	'inactive_account': 'Your account is inactivated. Please contact to the administrator to activate your account.',
	'account_activate_needed': 'Please activate your account from the link in your email before logging in OR contact the administrator to activate your account.',
	'user_created_success': 'User has been created Successfully.',
	'user_updated_success': 'User has been updated Successfully.',
	'user_listed_success': 'User has been listed successfully.',
	'OTPSent': "Your Authentication code sent to your registered email.",
	'no_user_found': 'No user has been found.',
	'user_details_success': 'User details has been listed successfully.',
	'user_deleted_success': 'User has been deleted successfully.',
	'user_status_changed': 'User status has been changed successfully.',
	'current_passsword_wrong': 'Current password is incorrect.',
	'password_need_different': 'You can not use old password. Please try to use new password.',
	'password_chagen_success': 'Password has been changed successfully.',
	'your_profile_update_success': 'Your profile has been updated successfully.',
	"verified_2factor": "Two factor verified successfully.",
	"invalid_token": 'Invalid 2-FA Code.',
	"qr_code_sent": 'QR code sent.',
	"two_factor_disabled": "Two Factor Authentication disabled successfully.",
	'two_factor_already_disabled': "Two Factor authentication is already disabled.",
	'upload_image_successfull': 'Image uploaded successfully.',
	'file_not_provided': 'Files are not provided.',
	'verify_success': 'KYC approved successfully.',
	'verify_reject': 'KYC disapproved successfully.',
	'role_created_success': 'Role has been created Successfully.',
	'role_updated_success': 'Role has been updated Successfully.',
	'role_listed_success': 'Role has been listed successfully.',
	'no_role_found': 'No role has been found.',
	'role_details_success': 'Role details has been listed successfully.',
	'role_deleted_success': 'Role has been deleted successfully.',
	'role_status_changed': 'Role status has been changed successfully.',

	'static_content_listed_success': 'Static content has been listed successfully.',
	'static_content_details_success': 'Static content details has been listed successfully.',
	'no_static_content_found': 'No static content has been found.',
	'static_content_updated_success': 'Static content has been updated Successfully.',

	'email_template_listed_success': 'Email Template has been listed successfully.',
	'no_email_template_found': 'No email template has been found.',
	'email_template_details_success': 'Email Template details has been listed successfully.',
	'email_template_updated_success': 'Eamil Template has been updated Successfully.',

	'limit_success': 'Limit Listed Successfully.',
	'loan_request_created_success': 'Loan Request Created Successfully.',
	'not_found_loan': 'No new loan request yet.',
	'loan_list_success': 'Data successfully listed.',
	'loan_request_updated_success': 'Loan Request has been updated Successfully.',
	'loan_request_success': 'Loan Request has been listed successfully.',
	'not_found_data': 'No data found.',

	'limit_created_success': 'Limit has been created Successfully.',
	'limit_updated_success': 'Limit has been updated Successfully.',
	'limit_success': 'Limit Details has been listed successfully.',

	'maximum_limit_error': 'Maximum Limit Exceeded.',
	'total_amount_error': 'Error in total_amount.',
	'installment_amount_error': 'Error in installment_amount.',
	'collateral_amount_error': 'You do not have enough balance in your wallet. Please add amount in your wallet.',
	'gas_fee': 'minimum gas fee required for future transaction.',
	'kyc_incomplete': 'please complete your kyc.',

	'notification_created_success': 'Notification has been created Successfully.',
	'notification_updated_success': 'Notification has been updated Successfully.',

	// Success Messages 
	'create': ' has been added sucessfully.',
	'update': ' has been updated sucessfully.',
	'delete': ' has been deleted sucessfully.',
	'list': ' has been listed sucessfully.',

	// Error Messages
	'not_create': ' has not been added.',
	'not_update': ' has not been updated.',
	'not_delete': ' has not been deleted.',
	'not_list': ' has not been listed.',
	'invalid_otp': 'Invalid OTP.',
	'transaction_fail': 'Transaction fail.',
	'late_payment': 'Late Payment.',

	// Email Templates
	'new_loan_request': 'New Loan Request.',
	'fund_release': 'Fund is released.',
	'liquidate_amout_credit': 'Liquidate amount is credited.',
	'due_installments': 'Due installments.',
	'loan_active_borrower': 'Congratulations... Your Loan is activated.',
	'loan_active_lender': 'Loan is activated.',
	'loan_terminate': 'Loan is terminated.',
	'loan_expire': 'Loan is about to expire.',
	'next_installment': 'Reminder - Next Payment Installment.',
	'place_collateral': " Collateral is placed.",
	'validate_collateral': "Validate Collateral.",
	'withdraw_collateral': "Loan Amount Withdrawn.",
	'collect_collateral': "Collateral is Collected.",
	'validate_lend': "Validate Lending Amount.",
	'payback_done': 'Payment Success.',
	'next_late_loan_installment': 'Reminder- Late loan installment.',
	'new_inquiry': "New Inquiry.",
	'inquiry_thanks': 'Thanks for contacting us! We will be in touch with you shortly.',
	'loan_request_not_accepted': 'This loan request has not been accepted 100%. So, the loan is terminated.',
	'borrower_not_accept_partially_fund': 'Borrower has not started this partially accepted loan, so the loan is terminated.',
	'borrower_not_paid_installment': 'Borrower has not paid installment, so the loan is terminated.',
	'partially_fund_loan_activate': 'Release Fund Amount.',
	'login_new_system': 'Security Alert.',
	'enable_twofa': 'Two Factor Enabled.',
	'disable_twofa': 'Two Factor Disabled.',
	'withdraw_ether': 'Withdraw Ether.',
	'withdraw_clpcoin': 'Withdraw CLP.',
	'change_password': 'Change Password.',
	'kyc_subject': 'KYC',
	'kyc_approved': 'KYC is approved.',
	'kyc_disapproved': 'KYC is not approved.',

	'email_username_used': 'Email and Username already in use.',
	'email_used': 'Email already in use.',
	'username_used': 'Username already in use.',
	'mobile_used': 'Mobile number already in use.',
	'file_not_upload': 'File not uploaded',
};